default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tq_cahspoint_development
  username: markpaul  # Replace this with your PostgreSQL username
  password: markpaul  # Replace with your PostgreSQL password
  host: localhost  # Add this if you're connecting to a local PostgreSQL instance
  port: 5432  # Ensure the port is set correctly if you're using a non-default PostgreSQL port

test:
  <<: *default
  database: tq_cahspoint_test
  username: markpaul  # Replace this with your PostgreSQL username
  password: markpaul  # Replace with your PostgreSQL password
  host: localhost  # Add this if you're connecting to a local PostgreSQL instance
  port: 5432  # Ensure the port is set correctly if you're using a non-default PostgreSQL port

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>